### ISSUE TITLE
The result of psnr

### ISSUE THREAD

**Issue by wangchx67** [MagicGeorge/RCTNet#1]
I have not train the network again, and I  just use the 500_net_F.pth  to calculate the psnr in LOL eval datasets, the final psnr is just 19.80, if it is your reproducement result?

**Comment by georgewuw** [comment]
I only remember that the code actually does not reach the PSNR and SSIM claimed in the paper. It may be that the specific details of the implementation are not fully given in the paper. By the way, I did not use bilateral filtering for post-processing.

**Comment by wangchx67** [comment]
> I only remember that the code actually does not reach the PSNR and SSIM claimed in the paper. It may be that the specific details of the implementation are not fully given in the paper. By the way, I did not use bilateral filtering for post-processing.

Could I get your fianl result(the PSNR and SSIM in fivek and LOL)?

**Comment by georgewuw** [comment]
Sorry, I am afraid I can not give you. I have no time to sort out these experimental results right now.
