### ISSUE TITLE
Unable to reproduce the performance of the paper

### ISSUE THREAD

**Issue by huangjch526** [MagicGeorge/RCTNet#3]
I can't reproduce the performance of this paper on MIT Adobe Fivek with your code. Could you please provide the train.py and test.py code on MIT Adobe Fivek? Or a trained model on MIT Adobe Fivek. Thank you very much.

**Comment by georgewuw** [comment]
Unfortunately, this project is unofficial, and indeed does not reach the performance in the paper. For Adobe Fivek, I use the method of scaling down the input image size with the longest side as 580(may be) , and then randomly cropping to 256 * 256

**Comment by huangjch526** [comment]
> Unfortunately, this project is unofficial, and indeed does not reach the performance in the paper. For Adobe Fivek, I use the method of scaling down the input image size with the longest side as 580(may be) , and then randomly cropping to 256 * 256

What was your PSNR in the experiment on MIT Adobe Fivek？

**Comment by georgewuw** [comment]
Sorry, it has been a long time. I am afraid that I can not find more things to help you.
